image: jakzal/phpqa:php8.1
before_script:
  - composer install

cache:
  paths:
    - vendor/
stages:
  - UnitTests

phpunit:
  image: php:8.1-apache
  stage: UnitTests
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: Devops2023!
    MYSQL_DATABASE: dbdevops
    MYSQL_USER: devops
    MYSQL_PASSWORD: Devops2023!
    DATABASE_URL: 'mysql://devops:Devops2023!@127.0.0.1:3306/dbdevops?serverVersion=8&charset=utf8mb4'
  before_script:
    - apt-get update && apt-get install -y git libzip-dev
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - docker-php-ext-install mysqli pdo pdo_mysql zip
    - php bin/console doctrine:database:drop --force --env=test
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:migration:migrate --env=test --no-interaction
  script:
    - php bin/phpunit
  allow_failure: false
