version: "3.8"
services:

  db:
    image: mysql:${MYSQL_TAG}
    container_name: "${PROJECT_NAME}_db"
    restart: always
    ports:
      - "8040:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/data/db-data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_TAG}
    container_name: "${PROJECT_NAME}_phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - "8050:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  symfony:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: docker/webserver
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ${SYMFONY_APP}:/var/www/html
    networks:
      - dev


networks:
  dev:

volumes:
  db-data: